### PR TITLE
✨ Add Processing info for ABBYY producer + the conversion itself

### LINKED ISSUE #15: Processing tags
I'm currently evaluating using this software to convert some ABBYY XML files and noticed that no ALTO `ocrProcessing`(v2)/`Processing`(v4) tags are generated. 

I'm working on a PR to add these!

### PR DESCRIPTION
**Pull request by mikegerber**
- [x] Add processing step for ABBYY producer
- [x] Add processing step for the conversion itself
- [x] Review for "Java idiomacy" of the PR 
- [x] Add for ALTOv2?

Closes #15.

### CODE REVIEW

**Comment by mikegerber** [comment]
This produces `Processing` (ALTO4) or `OCRProcessing` (ALTO2) tags in the output:

~~~xml
    <Description>
        <MeasurementUnit>pixel</MeasurementUnit>
        <Processing>
            <processingSoftware>
                <softwareName>ABBYY FineReader Engine 11</softwareName>
            </processingSoftware>
        </Processing>
        <Processing>
            <processingDateTime>2022-06-27</processingDateTime>
            <processingSoftware>
                <softwareName>abbyy-to-alto</softwareName>
            </processingSoftware>
        </Processing>
    </Description>
~~~

I'm a little inexperienced writing Java code, so please review :)

**Comment by mikegerber** [comment]
Reverting to Draft, the output does not validate against the schema yet.

~~~
00000834.alto.xml:5: element OCRProcessing: Schemas validity error : Element '{http://www.loc.gov/standards/alto/ns-v2#}OCRProcessing': The attribute 'ID' is required but missing.
00000834.alto.xml:12: element OCRProcessing: Schemas validity error : Element '{http://www.loc.gov/standards/alto/ns-v2#}OCRProcessing': The attribute 'ID' is required but missing.
00000834.alto.xml fails to validate
~~~

**Comment by mikegerber** [comment]
The produced ALTO2 files validate now and I think this is ready for review/merge!

~~~
% xmllint --noout -schema ~/Downloads/alto2.xsd 00000834.alto.xml
00000834.alto.xml validates
~~~

**Comment by Mewel** [comment]
Looks ok :)

**Pull request merged**
