### PR TITLE
Added support for lang and glyphs in Alto version 4.1

### PR DESCRIPTION
**Pull request by jschwertfeger**
Code is completely backwards compatible; i.e. the CLI still functions with the original logic and produce v2 output.

### CODE REVIEW

**Comment by Mewel** [comment]
Thanks for the pull request. Just two little things:
1. Could you add a test case with an alto v4 xml file
2. I think it would be best to update the version from 0.1-SNAPSHOT to 0.2-SNAPSHOT. Otherwise it will not be backwards compatible cause you removed the JAXBUtil#marshalToAlto() methods and didn't make them deprecated (which is totally fine for a new version)

I would merge this pull request after. Thanks!

**Comment by jschwertfeger** [comment]
Done. I also added `JAXBUtil#marshalToAlto()` back in to stay compatible.

**Comment by Mewel** [comment]
Hm, I don't see any changes in the branch (neither in github nor in intellij). Did I do something wrong or did you just commit/push on your forked branch?

**Comment by jschwertfeger** [comment]
I squashed the commits into the original one and force-pushed it. The original pull request contains all of it now (see the tests at https://github.com/Mewel/abbyy-to-alto/pull/6/commits/88f47c5610a2d7f3e2d29d231307630deac4edb1#diff-52fc8083e9938a80ef08d308c9643011 for instance)

**Comment by jschwertfeger** [comment]
Maybe a force-push was not the nicest thing to do as a pull to your local machine will not pull in the head again. It's probably easiest if you delete your local merge request branch and check it out again.

**Comment by Mewel** [comment]
Jep you right :). Merged it!

**Pull request merged**
